// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./../../pages/404.vue')['default']
    AdminDashboard: typeof import('./../../pages/adminDashboard/index.vue')['default']
    AdminMenuDrawer: typeof import('./../../components/drawer/AdminMenuDrawer.vue')['default']
    BaseModal: typeof import('./../../components/modals/BaseModal.vue')['default']
    BDrawer: typeof import('./../../components/drawer/BDrawer.vue')['default']
    DarkModeToggle: typeof import('./../../components/content/DarkModeToggle.vue')['default']
    DashboardItem: typeof import('./../../components/dashboard/DashboardItem.vue')['default']
    EmployeeEventItem: typeof import('./../../components/employees/EmployeeEventItem.vue')['default']
    EmployeeUserItem: typeof import('./../../components/employees/EmployeeUserItem.vue')['default']
    EventItem: typeof import('./../../components/events/EventItem.vue')['default']
    EventUserItem: typeof import('./../../components/events/EventUserItem.vue')['default']
    Footer: typeof import('./../../components/footer/Footer.vue')['default']
    Header: typeof import('./../../components/header/Header.vue')['default']
    HeaderList: typeof import('./../../components/header/HeaderList.vue')['default']
    Index: typeof import('./../../pages/Index.vue')['default']
    Loader: typeof import('./../../components/content/Loader.vue')['default']
    Login: typeof import('./../../pages/login.vue')['default']
    LoginModal: typeof import('./../../components/modals/LoginModal.vue')['default']
    MenuDrawer: typeof import('./../../components/drawer/MenuDrawer.vue')['default']
    Select: typeof import('./../../components/content/Select.vue')['default']
    SimpleLogo: typeof import('./../../components/logo/SimpleLogo.vue')['default']
    StepBubble: typeof import('./../../components/content/StepBubble.vue')['default']
    Switch: typeof import('./../../components/forms/Switch.vue')['default']
    UserDashboard: typeof import('./../../pages/userDashboard/index.vue')['default']
    Userform: typeof import('./../../components/users/Userform.vue')['default']
    Users: typeof import('./../../pages/adminDashboard/Users.vue')['default']
    UsersAdminModal: typeof import('./../../components/modals/UsersAdminModal.vue')['default']
  }
}

export { }
