// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./../../components/header/Header.vue')['default']
    Index: typeof import('./../../pages/Index.vue')['default']
    Login: typeof import('./../../pages/login.vue')['default']
    LoginModal: typeof import('./../../components/modals/LoginModal.vue')['default']
  }
}

export { }
