// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./../../pages/404.vue')['default']
    AdminDashboard: typeof import('./../../pages/adminDashboard/index.vue')['default']
    AdminMenuDrawer: typeof import('./../../components/drawer/AdminMenuDrawer.vue')['default']
    Header: typeof import('./../../components/header/Header.vue')['default']
    Index: typeof import('./../../pages/Index.vue')['default']
    Login: typeof import('./../../pages/login.vue')['default']
    LoginModal: typeof import('./../../components/modals/LoginModal.vue')['default']
    MenuDrawer: typeof import('./../../components/drawer/MenuDrawer.vue')['default']
    SimpleLogo: typeof import('./../../components/logo/SimpleLogo.vue')['default']
    UserDashboard: typeof import('./../../pages/userDashboard/index.vue')['default']
  }
}

export { }
